# Generated by Django 2.1.2 on 2018-10-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('npm', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Quorum',
        ),
    ]
