# Generated by Django 2.1.2 on 2018-10-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0002_auto_20181029_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('nilai_saldo', models.IntegerField()),
            ],
        ),
    ]
