# Generated by Django 2.1.2 on 2018-10-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ewallet', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nama',
            field=models.CharField(default='', max_length=50),
        ),
    ]
